services:
  poylmarket-stocks-hedging:
    build: .
    image: polymarket-stocks-hedging
    container_name: polymarket-stocks-hedging
    ports:
      - "50003:3000"
    env_file:
      - .env
    volumes:
      - ./config:/app/config:ro
      - ./data:/app/data
    restart: always
